sudo: required
services:
  - docker
env:
  global:
    # Environment variable for the image tags.
    - SHA=$(git rev-parse HEAD)
    # Another env. variable for the Google Cloud CLI
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # Google Cloud configuration:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project udemy-docker-multi-k8s
  - gcloud config set compute/zone europe-central2-a
  - gcloud container clusters get-credentials udemy-docker-multi-cluster
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build test version...
  - docker build -t tlambeck/react-test -f ./client/Dockerfile.dev ./client

script:
  # ... and run tests
  - docker run -e CI=true tlambeck/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
