sudo: required
services:
  - docker

before_install:
  - docker build -t th-lamb/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run th-lamb/react-test npm run test -- --coverage
  - docker run -e CI=true th-lamb/react-test npm test

after_success:
  # Build prod images for the 4 services (using the 
  # default filename "Dockerfile").
  - docker build -t tlambeck/udemy-docker-multi-client ./client
  - docker build -t tlambeck/udemy-docker-multi-nginx ./nginx
  - docker build -t tlambeck/udemy-docker-multi-server ./server
  - docker build -t tlambeck/udemy-docker-multi-worker ./worker

  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to Docker Hub.
  - docker push tlambeck/udemy-docker-multi-client
  - docker push tlambeck/udemy-docker-multi-nginx
  - docker push tlambeck/udemy-docker-multi-server
  - docker push tlambeck/udemy-docker-multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'udemy-docker-multi'
  env: 'Udemydockermulti-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-121986536897'
  bucket_path: 'udemy-docker-multi'
  # Only deploy for the master branch!
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
