sudo: required
services:
  - docker

before_install:
  - docker build -t th-lamb/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run th-lamb/react-test npm run test -- --coverage
  - docker run -e CI=true th-lamb/react-test npm test

after_success:
  # Build prod images for the 4 services (using the 
  # default filename "Dockerfile").
  - docker build -t tlambeck/multi-client ./client
  - docker build -t tlambeck/multi-nginx ./nginx
  - docker build -t tlambeck/multi-server ./server
  - docker build -t tlambeck/multi-worker ./worker

  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to Docker Hub.
  - docker push tlambeck/multi-client
  - docker push tlambeck/multi-nginx
  - docker push tlambeck/multi-server
  - docker push tlambeck/multi-worker
