# Updated according to https://ausytechnologies.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11628292#questions/8077138
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: data    # postgres-storage
          persistentVolumeClaim:
            claimName: data   # database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres         # Just the standard version
        ports:
        - containerPort: 5432   # Postgres default port
        volumeMounts:
          - mountPath: /var/lib/postgresql/data   # postgres data folder
            subPath: data   # postgres   # subfolder inside the volume claim
            name: data    # postgres-storage
        env:
          - name: POSTGRES_PASSWORD   # not PGPASSWORD anymore due to changes in Postgres!
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
        # The IDE suggests resource limits!
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
